name: Churn and Complexity Analysis

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Run analysis
      run: docker pull sebastiancotrina/refactorthis:latest && docker run --name refactorthis -v $PWD:/project sebastiancotrina/refactorthis:latest
    - name: Execute
      run:  docker exec refactorthis ../entrypoint.sh
    - name: Get Image
      run: docker exec refactorthis mv complexity_vs_churn.png /project