name: Churn and Complexity Analysis

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Run analysis
      run: docker pull sebastiancotrina/refactorthis:latest && docker run -v $PWD:/project sebastiancotrina/refactorthis:latest
