name: Churn and Complexity Analysis

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Pull Docker Image
      run: docker pull sebastiancotrina/refactorthis:latest

    - name: Start Docker Container
      run: docker run -d --name refactorthis -v $PWD:/project sebastiancotrina/refactorthis:latest tail -f /dev/null

    - name: Execute Analysis
      run: docker exec refactorthis ../entrypoint.sh

    - name: Retrieve Image
      run: docker cp refactorthis:/app/complexity_vs_churn.png $PWD/complexity_vs_churn.png

    - name: Cleanup
      run: docker stop refactorthis && docker rm refactorthis
